INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Health_mod`, `Mana_mod`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified`) VALUES ('500998', '0', '0', '0', '0', '0', '21701', '0', '0', '0', 'Belbi Quikswitch', 'Token Redeemer', '', '8783', '65', '65', '0', '875', '875', '131', '1', '1.14286', '1', '0', '200', '281', '0', '278', '1', '2000', '0', '1', '33536', '8', '0', '0', '0', '0', '0', '166', '246', '35', '7', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '3', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '', '12340');
UPDATE `creature_template` SET `ScriptName`='mga_promo_code' WHERE (`entry`='500998');
UPDATE `creature_template` SET `faction_A`='35', `faction_H`='35', `npcflag`='1', `unit_flags`='0' WHERE (`entry`='500998');
UPDATE `creature_template` SET `name`='', `subname`='MGA Promo Codes' WHERE (`entry`='500998');
UPDATE `creature_template` SET `subname`='Enter Promo Codes Here' WHERE (`entry`='500998');
UPDATE `creature_template` SET `name`='Kelsey Ironspark' WHERE (`entry`='500998');

INSERT INTO `script_texts` (`npc_entry`,`entry`,`content_default`) VALUES ('500911','-1720500','You have all ready redeemed you r promo code.');
INSERT INTO `script_texts` (`npc_entry`,`entry`,`content_default`) VALUES ('500911','-1720501','Your inventory is full, please make sure you have at least one free slot.');
INSERT INTO `script_texts` (`npc_entry`,`entry`,`content_default`) VALUES ('500911','-1720502','Unexpected technical error. Please inform a Staffmember.');
INSERT INTO `script_texts` (`npc_entry`,`entry`,`content_default`) VALUES ('500911','-1720503','There you go! Check your bags for your reward.');
INSERT INTO `script_texts` (`npc_entry`,`entry`,`content_default`) VALUES ('500911','-1720504','Good bye!');
UPDATE `script_texts` SET `content_default`='You have all ready redeemed your promo code.' WHERE (`npc_entry`='500911') AND (`entry`='-1720500');
INSERT INTO `script_texts` (`npc_entry`,`entry`,`content_default`) VALUES ('500911','-1720505','The code you entered is not known...');
UPDATE `item_template` SET `minMoneyLoot`='50000', `maxMoneyLoot`='80000' WHERE (`entry`='10456');
